### ISSUE TITLE
merge-bot failing with error on pull request

### ISSUE THREAD

**Issue by ChrisRBe** [squalrus/merge-bot#47]
Hi @squalrus,

thank you for this handy bot. Great stuff.

I just set up an action on one of my repositories that is for now private and only worked on by me.

When running the action in "live" mode I get the following error message:

```
[data] pull (checks + reviews): {"labels":["merge"],"owner":"ChrisRBe","pull_number":6,"reviews":{},"ref":"11d02790cec54a9b1bbfe445d164e4c7fb0af1b1","repo":"kitcheneer","requested_reviewers":[],"checks":{"total":5,"completed":4,"success":4}}
merge: true
Error: Reference does not exist
```

Do you have an idea what is happening here?

**Comment by squalrus** [comment]
Hey, thanks for reaching out! A couple questions:

1. Do you happen to be using the "checks" feature?
2. Do you mind sharing a pull request where this ran? I'd be happy to help debug.

**Comment by ChrisRBe** [comment]
Hey,
I just gave you access to the repository in question. One of the PRs affected by it would be this one here:
https://github.com/ChrisRBe/kitcheneer/pull/6

And yes, I am using the checks feature as you can see from the merge-bot config in this PR:
`checks_enabled: true`

**Comment by squalrus** [comment]
Thanks for the access.

Correct me if I'm wrong, but it seems like merge-bot was able to integrate https://github.com/ChrisRBe/kitcheneer/pull/6, https://github.com/ChrisRBe/kitcheneer/pull/7, and https://github.com/ChrisRBe/kitcheneer/pull/8

Assuming the integration happened correctly, I suspect the issue is with the [`delete_source_branch`](https://github.com/ChrisRBe/kitcheneer/blob/a781942dcf4b2e9457b7ec536dd0953b927237f0/.github/workflows/merge-bot.yml#L32).

In your [repo settings](https://github.com/ChrisRBe/kitcheneer/settings), do you happen to have the following checked? If so, it _could_ be deleting the branch before merge-bot is able to delete. (I don't believe this is the case since it appears you manually deleted the branches of the PRs several minutes after integrating, but thought I'd ask.)

![image](https://user-images.githubusercontent.com/1166426/108611308-50073080-7392-11eb-80c0-0260b0b286b1.png)

It is also very possible merge-bot has a bug. I am going to try testing in another repo of mine, see if I can reproduce.

**Comment by ChrisRBe** [comment]
Hey,

Thank you for checking. I checked the repo settings on my side and this particular setting is not set. 

Overall: Yes, the bot is able to merge the PR but the final branch deletion seems to be bugged? It seems that this is also blocking a follow up build on the main branch.

**Comment by squalrus** [comment]
I am able to reproduce in another one of my repositories: https://github.com/squalrus/squalr.us/pull/19

To unblock you now, I'd recommend updating `delete_source_branch` to `false` and using the built in setting (mentioned above).

I will look into this further and test. Thanks again for raising the issue.

**Comment by ChrisRBe** [comment]
That's great news. Or maybe not :)
Thank you for the quick response! I will change the repo settings as suggested tomorrow

________________________________

**Comment by squalrus** [comment]
I made a few updates and the issue is hopefully resolved. Feel free to try out [`v0.4.4`](https://github.com/squalrus/merge-bot/releases/tag/v0.4.4) and let me know!

**Comment by ChrisRBe** [comment]
@squalrus thanks again for the fast feedback. PRs are correctly closed now :) 
Thank you for your work.
